### ISSUE TITLE
contrib/pull requests

### ISSUE THREAD

**Issue by daed** [TurningWheel/Barony#12]
I didn't know where else to put this, but I'm very interested in this game and want to see it improved.

I was wondering if there was any overall thing that needed to be done to get pull requests approved or be added as a contributor to the project.  I've put quite a bit of work in already helping in the official bug reporter as "bradarnett", and I'd like to continue work first hand if possible.

**Comment by addictgamer** [comment]
We don't really have any process or "overall thing" that needs to be done for pull requests to be approved. Just make a pull request -- Somebody (I, at this point in time) will review it, let you know if there any issues, and once all concerns have been addressed, you can expect the request to be accepted.
Honestly, unless we have problems with poor code or people haphazardly changing game balance, I think most reasonable pull requests should be accepted without too much hassle.

So far, we've gotten about half a dozen pull requests from one user, and most of their changes can now be found in the codebase :)
I hope to keep it that way!

**Comment by daed** [comment]
I appreciate the concise and prompt answer.  One other question:  do you know how does the git repo translates into the official releases?  Is there a scheduled "official" release that is built from the repo, or is it just on more of a "we've got enough for a release" timeline?

**Comment by addictgamer** [comment]
So far, we're going more along the lines of "we've got enough for a release" timeline, although I do have a sort of checklist in my mind for things I want to see finished before we push out another official release.

I actually have some files, emails, and scribbled notebooks/sheets of paper sitting around here with things I want to see done at some point in time. They don't particularly have any sort of timeline, it's more of just a bunch of notes, TODOs, and various ideas I've been scribbling and erasing things from since I've joined the project.
Perhaps I could gather what I can and stick it up somewhere, just so that any interested parties could take a gander at it.

**Comment by daed** [comment]
That could be useful.  There's a TODO, but I could be interested in working on things of that like.

**Comment by addictgamer** [comment]
Ok, I'll see what I can pull up.

**Comment by addictgamer** [comment]
56d3e0658bcec2ab2c8a3f06e5ed57f456eac1dc: Added some of the files I found laying around.

**Comment by akien-mga** [comment]
I guess this issue could be closed now, but maybe a CONTRIBUTING.md file could be added with some initial instructions for interested contributors.

**Comment by addictgamer** [comment]
I've begun preparing such a file, in addition to throwing together some semblance of coding style guidelines (something much needed for this code).
