### ISSUE TITLE
[2.0.7][Audio] Troll walking sound will spam when woken up while partially in a wall

### ISSUE THREAD

**Issue by crkellen** [TurningWheel/Barony#259]
**ISSUE:**
When a sleeping Troll is woken up by hitting them, the Troll's walking sound will spam (for roughly 1 second if they are partially within a wall). It creates a loud 'DRRR' sound.

**EXPECTED RESULT:**
Audio should never spam.

**STEPS TO REPRODUCE:**
1. Start a game
2. Spawn a Troll until you have a sleeping one
3. Stand a bit away from it and hit it, waking it up. It will play the sound as it begins to pathfind towards the Player
4. To spawn one in a wall, go to any corner and look at the corner then spawn one, in most cases it will spawn within a wall.

**ADDITIONAL INFO:**
This was originally reported by @gustaf-kingq who experienced it multiple times throughout a normal run through the labyrinth. This report can be seen on the Discord server in #bug-reports. This issue exists in both FMOD and OpenAL.

**Comment by WALLOFJUSTICE** [comment]
Addressed in commit 10b9c5f08bb8e8fcd668ec1bc3cef48131e53788. 

This was a race condition between the leg pitches on wakeup, as they are set to same direction -PI/2 when sleeping. 

When they'd wake up, the right leg would cause a sound, then reverse the direction (good behaviour). Then the left leg would change polarity since it also was negative, and then the right leg would go back to it's previous pitch (causing a sound the next frame again). They still might spasm their limbs a little but it's not 100% like before.

**Comment by WALLOFJUSTICE** [comment]
Merged, fixed.
