### ISSUE TITLE
Ice Storm Triple XP

### ISSUE THREAD

**Issue by dhakim87** [TurningWheel/Barony#420]
The multi attack potions appear to triple kill enemies, rewarding their experience multiple times.  To see this, make a goatfolk brewer, brew two ice storms, and toss them both at a troll.  You will immediately gain 3 levels.  

Admittedly, this is the only way the goatfolk brewer can survive the early game :P

**Comment by WALLOFJUSTICE** [comment]
Nice pickup! Confirmed - Troll at player LVL one provides 1 LVL, while storm potion gives 3 LVLs.

The 3 projectiles auto-hit the target (since trying to use the actual projectiles would only sometimes hit 1 or 2 times). Auto-hitting should check if HP is > 0 before declaring it made an impact.



No urgent plans to fix this so will keep open until next patch hits.

**Comment by WALLOFJUSTICE** [comment]
Fixed in 7ebd4bb1
