### ISSUE TITLE
Polymorph + Water

### ISSUE THREAD

**Issue by dhakim87** [TurningWheel/Barony#421]
Towards further screwing over the poor goatfolk:

Polymorph + Water -> Polymorph + Random Potion

The polymorph potion is regularly unused, at least with goatfolk brewer, but every other polymorph + X potion uses both.  

This is inconsistent with every other potion recipe and I don’t see it on any guides.  If this isn’t a bug like a missing return letting the water dup the poly (or maybe even if it is), can you add a special message:

“Your water is transformed!”

Sigh, if brewer gets any worse, I’ll never finish brawlermode

**Comment by WALLOFJUSTICE** [comment]
Sorry what's your expected outcome? And what currently happens with polymorph and water/potions?

**Comment by dhakim87** [comment]
Current behavior:

If you combine Water and X, you either get a message that your X has dissolved into water, or your water has been brewed into X.  

If you combine water and polymorph, your polymorph never (?) dissolves into water, instead your water always transforms into a random potion.  

If you combine polymorph and X, both potions are lost to brew one random potion. 

—

This means that sitting on a single polymorph potion to make use of the endless water potions you get from sinks is absolutely critical early on, but it is completely unclear to the user that water and X behave differently when mixing with polymorph.  The message you get is identical, so you have to carefully watch your potion stocks to figure out what’s going on.  

I think the current set of reactions is fine, but request that a special feedback message is added to the water + polymorph reaction, to indicate to the user that it is somehow special.

**Comment by WALLOFJUSTICE** [comment]
Oh I see.. definitely a bug. It's the duplication of water getting in the way here.

What SHOULD happen.. Polymorph + Water = lose both ingredients, get 1 random potion out of it. This happens <50% of the time.

When the duplication check succeeds (because one of the ingredients is water), it consumes only the water, and leaves you with the 1x polymorph and 1x new random potion. Which is not intended.

Reason I haven't picked up on it is that it's chance based bug!

**Comment by WALLOFJUSTICE** [comment]
Fixed in e2adaf54
