### ISSUE TITLE
Multithreaded Pathfinding

### ISSUE THREAD

**Issue by addictgamer** [TurningWheel/Barony#46]
If possible, multi-threading the pathfinding code would definitely improve performance.

Due to the enormity of this task, I am not planning on tackling this in the near future. It may not even be possible with this codebase, due to such issues as thread safety. As such, I am putting this up for posterity's sake -- populating the "Performance Improvements" milestone with ideas/tasks that should increase performance.

**Comment by WALLOFJUSTICE** [comment]
What would you say is the most performance demanding part of the pathfinding? I found with mob spawns of 15+ the frames would only drop some of the time, but obviously more consistently at higher amounts.

Every mob checks every entity on the map through it's WAIT and HUNT state until it finds something to interact with, could there be much of an improvement to limiting the search range to the vision distance before processing direction or the target light levels?

**Comment by SheridanR** [comment]
I would absolutely start this task by sorting different object types into different lists entirely, rather than having one enormous list of entities which is crawled through linearly every time we want to look up the object. The dangerous part is that the pointers in the entity list are the only "owners" of the object right now, and if you add additional lists referencing the same objects then you can end up creating dead references. For this reason we'd need a shared pointer system, and I wouldn't necessarily use the one that comes stock with C++ (convenient as it is) though that would certainly be a start.

At that point, I would also go the extra mile and replace the entity lists with hash tables, where the entity uid effectively takes the place of the hash (thus acting as the key index for an array of lists). That would greatly improve entity lookup times, which is important for speeding up other areas of the code (though a bit tangential to this issue...)

Finally, you'd have to deal with thread-safety. How do you find the path while entities are still moving in the world and changing the terrain? It wouldn't be too difficult to generate and pass an obstacle map to the thread which it can then use to find the path, rather than working with the raw level data... in fact, that would solve most of your problems right there. For an example on how to copy and store level data in memory, you could reference the undo/redo functions for the editor in editor.cpp.

Those are my thoughts on this :)

**Comment by WALLOFJUSTICE** [comment]
Well 2 years later.. I can say we finally got somewhere.
Pathfinding now uses "entities on tile" checking rather than looping through every entity at every tile, generatePathMaps() as such longer a big deal, no lag when mining blocks.
Lots of entity lists were replaced by a creature-list which only needs to traverse the 20-30 monsters on a map instead of 600 entities.
