### ISSUE TITLE
FreeBSD - error: unable to locate language file: 'lang/en.txt'

### ISSUE THREAD

**Issue by Adrien2002** [TurningWheel/Barony#538]
Hello there !

I downloaded the Linux version from GOG (3.3.7) and extracted the game files into _/home/$USER/Games/Barony_ (so, for example, I have _/home/$USER/Games/Barony/lang/en.txt_)

I cloned the git repository and built Barony then moved both "**barony**" and "**editor**" binaries inside _/home/$USER/Games/Barony_

I change directory to _/home/$USER/Games/Barony_ then I do ./barony (so I'm in the same folder as the "lang" folder) but the game won't start. Instead, I have this : 

```
[20-10-11] Binary path: /usr/home/Adrien2002/Games/Barony/barony
[20-10-11] Chrooting to directory: /usr/home/Adrien2002/Games/Barony
[20-10-11] Data path is ./
[20-10-11] Output path is /home/Adrien2002/.barony
```

And _/home/$USER/.barony/log.txt_ says :

```
[19-54-22] error: unable to locate language file: 'lang/en.txt'
[19-54-22] Fatal error: failed to load default language file!
```

Why Barony doesn't find lang/en.txt ?

**Comment by devnexen** [comment]
What happens if you do
`./barony -data=~/Games/Barony`

or at build time

`cmake -DBASE_DATA_DIR=/home/Adrien2002/Games/Barony
...
./barony` ??

**Comment by Adrien2002** [comment]
`-data=~/Games/Barony` as an option didn't do the trick but `-DBASE_DATA_DIR=/home/Adrien2002/Games/Barony` helped, the game now starts.

`[21-52-54] Data path is /home/Adrien2002/Games/Barony`

I wonder why Barony can't find lang/en.txt throught `./` though.

Thank you very much, **devnexen**.

**Comment by paulwratt** [comment]
At a glance, I woulds say this is a bug, Barony not checking `./` (this folder) first, before trying anything else (like loading environment variables or overrides.

It also begs the questions, why this `./barony -data=~/Games/Barony` override did not work, and why in both cases is there a need for a _hard_ _coded_ _path_. Surely `./` would be more acceptable as a default or fall-back in all cases

I would like so see this reopened and addressed, as it should not happen, and should be a 5min (or less) fix. If it is not a 5min fix, then that too begs further questions, which probably should be addressed sooner rather than later.

**Comment by devnexen** [comment]
I think I got an idea what is wrong, I ll propose a PR.

**Comment by devnexen** [comment]
I think I got an idea what is wrong, I ll propose a PR.
